swagger: "2.0"
info:
  version: 0.0.1
  title: Approximate Nearest Neighbor [ANN] Server
host: localhost:8000

paths:
  /:
    get:
      summary: Healthcheck for service
      responses:
        "200":
          description: An array of loaded ANN indexes (Healthcheck)
          schema:
            type: array
            items:
              type: string
            example: ["INDEX-0","INDEX-1","INDEX-2"]
  /tmp:
    get:
      summary: Get size of /tmp
      responses:
        "200":
          description: Size of /tmp in megabytes
          schema:
            type: int
            example: 256
  /sleep:
    get:
      summary: Sleep for `duration` milliseconds
      parameters:
        - name: duration
          description: duration in milliseconds to sleep
          type: string
  /ann/{indexName}:
    get:
      summary: Healthcheck for specific ANN index
      operationId: showAnnByName
      parameters:
        - name: indexName
          in: path
          required: true
          description: The name of the ANN index
          type: string
      responses:
        "200":
          description: ANN Metadata (Healthcheck)
          schema:
            $ref: '#/definitions/ann_summary'

  /ann/{indexName}/query:
    post:
      summary: Query the ANN index for neighbors
      operationId: queryAnn
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: indexName
          in: path
          required: true
          description: The name of the ANN index
          type: string
        - name: idsPayload
          in: body
          description: Query payload
          schema:
            $ref: '#/definitions/query_payload'
      responses:
        "200":
          description: list of neighbors
          schema:
            $ref: '#/definitions/entity_ids'

  /crossq:
    get:
      summary: Query the ANN with an entry from another ANN index
      operationId: crossQueryAnn
      produces:
        - application/json
      parameters:
        - name: q_name
          required: true
          description: The name of the ANN index to grab query *from*
          type: string
        - name: q_id
          required: true
          description: Name of the particular record to use as the query
            (must be a member of the `q_name` index)
          type: string
        - name: catalog_name
          required: true
          description: The name of the ANN index to apply query *to*
          type: string
        - name: k
          required: true
          description: number of neighbors to get
          type: int
        - name: incl_dist
          required: true
          description: if true, include associated distances
          type: bool
      responses:
        "200":
          description: list of neighbors
          schema:
            oneOf:
              - $ref: '#/definitions/entity_ids'
              - $ref: '#/definitions/entity_ids_w_dists'

  /ann/{indexName}/refresh:
    post:
      summary: Reload the particular ANN index (may take some time)
      operationId: reloadAnn
      parameters:
        - name: indexName
          in: path
          required: true
          description: The name of the ANN index
          type: string
      responses:
        "200":
          description: Index successfully reloaded

definitions:
  entity_id:
    type: string
    example: '123'
  entity_id_w_dist:
    type: array
    example: ["123", 0.9]
  entity_ids:
    type: array
    items:
      $ref: '#/definitions/entity_id'
    example: [ "123", "456", "789"]
  entity_ids_w_dists:
    type: array
    items:
      $ref: '#/definitions/entity_id_w_dist'
    example: [ ["123", 0.9], ["456", 0.8], ["789", 0.1]]


  query_payload:
    required: ['id', 'k']
    properties:
      id:
        $ref: '#/definitions/entity_id'
      k:
        description: number of neighbors to get
        type: integer
        example: 5
      search_k:
        description: (UNUSED) number of nodes to inspect (leave as -1 if unsure)
        type: integer
        example: -1

  ann_summary:
    properties:
      path_tar:
        type: string
        example: 'my-bucket/ann/INDEX-0.tar.gz'
      ann_meta:
        properties:
          vec_src:
            type: string
            example: 'dynamoDB:repr-table'
          metric:
            type: string
            example: 'angular'
          n_dim:
            type: integer
            example: 1024
          timestamp_utc:
            type: string
            example: '2019-04-16T03:21:17.040380'
      ts_read:
        type: integer
        example: '2019-04-16T14:40:39+00:00'
      n_ids:
        type: integer
        example: 5906
      head5_ids:
        $ref: '#/definitions/entity_ids'
